server:
  port: 8088

logging:
  level:
    org:
      springframework: debug
spring:
  application:
    name: SpringAIDemo
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springai?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  ai:
    ollama:
      base-url: http://10.160.4.68:11434
      chat:
          model: qwen3:8b
          temperature: 0.7
      embedding:
        model: nomic-embed-text
    vectorstore:
      milvus:
        client:
          host: 172.21.160.1
          port: 19530
          username: root
          password: milvus
        databaseName: default
        collectionName: vector_store
        embeddingDimension: 768
        indexType: IVF_FLAT
        metricType: COSINE
        initialize-schema: true
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:schema-mysql.sql
jwt:
  user-secret-key: u1kP3vZ7jH9Df+2QZqfy1zSBl3F4W8NtV5HrOXLeElU=
  user-ttl: 7200000
  user-token-name: Authorization

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.SpringAIDemo.entity
  configuration:
    map-underscore-to-camel-case: true